# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# Song.create!( name: '1997', band: 'Hatten', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: '20 e poucos anos', band: 'Raimundos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'A Cera', band: 'O Surto', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'A dois passos do paraiso', band: 'Blitz', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'A Estrada (Acustico)', band: 'Cidade Negra', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'A sombra da maldade', band: 'Raimundos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'A sua maneira', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Acima do Sol', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Agora So Falta Você', band: 'Rita Lee', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Ainda e Cedo', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Al Capone', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'All Star ', band: 'Cassia Eller', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Aluga-se', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Amei te ver', band: 'Tiago Iorc', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Amor pra recomecar', band: 'Frejat', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Andei So', band: 'Natiruts', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Anjos', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Anna Julia', band: 'Los Hermanos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Anunciacao', band: 'Alceu Valenca', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Aonde Quer Que Eu Va', band: 'Paralamas Do Sucesso', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Apenas Mais Uma De Amor', band: 'Lulu Santos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Assim Caminha A Humanidade', band: 'Lulu Santos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Astronauta De Marmore', band: 'Nenhum De Nos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Bete Balanco', band: 'Barao Vermelho', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Bichos Escrotos', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Boa Sorte', band: 'Vanessa Da Mata', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Bois Don`t Cry', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Borbulhas De Amor', band: 'Fagner', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Burguesinha', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Camila Camila', band: 'Nenhum De Nos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Capim Guine', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Carla', band: 'LS Jack', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Carta aos missionarios', band: 'Uns E Outros', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Cedo Ou Tarde', band: 'NX Zero', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Cegos Do Castelo Os', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Chao De Giz', band: 'Ze Ramalho', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Chopis centes', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Ciumes', band: 'Ultraje A Rigor', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Codinome Beija-Flor', band: 'Cazuza', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Com Certeza', band: 'Planta e Raiz', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Como Eu Quero', band: 'Kid Abelha', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Cowboy fora da lei', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Cuide Bem Do Seu Amor', band: 'Paralamas Do Sucesso', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Daniel Na Cova Dos Leoes', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Deixa', band: 'Lagum', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Descobridor Dos 7 Mares', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Dezesseis', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Dias Atras', band: 'CPM 22', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Dias De Luta', band: 'Ira', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Do Lado De Ca', band: 'Chimarruts', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'E Preciso Saber Viver', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eduardo e Monica', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Ela Disse Adeus', band: 'Paralamas Do Sucesso', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Ela Roubou Meu Caminhao', band: 'Matanza', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Ela Vai Voltar', band: 'Charlie Brown Jr', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Envelheco na cidade', band: 'Ira', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Epitafio', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Era Um Garoto', band: 'Engenheiros  Os Incriveis', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Esperando Na Janela', band: 'Cogumelo Plutao', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu Amo Mais voce', band: 'Catedral', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu Nasci A 10 mil Anos Atras', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu quero ver o oco', band: 'Raimundos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu Sei', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu Sei', band: 'Papas da Lingua', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu Vou Estar', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Exagerado', band: 'Cazuza', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Facil', band: 'Jota Quest', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Faroeste Caboclo', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Fatima', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Fogo', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Garcom', band: 'Reginaldo Rossi', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Garganta', band: 'Ana Carolina', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Garota Nacional', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Garotos II', band: 'Leoni', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Geraaoo Coca-Cola', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Gostava tanto de vc', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Hey Joe', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'I Saw You Saying', band: 'Ramones', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Independencia', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Indios', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Inutil', band: 'Ultraje A Rigor', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Jackie tequila', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Jumento Celestino', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'La Bella De Jour', band: 'Alceu Valenca', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Girassol', band: 'Alceu Valenca', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'La Vem O Alemao', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Lado B Lado A', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Lagrimas e Chuva', band: 'Kid Abelha', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Luz Dos Olhos', band: 'Cassia Eller', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Maluco beleza', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Mantenha o respeito', band: 'Planet Hemp', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Marvin', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Mascara', band: 'Pitty', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Me Adora', band: 'Pitty', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Me Deixa', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Me Lambe', band: 'Raimundos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Menina Veneno', band: 'Ritche', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Meninos e Meninas', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Meu Abrigo', band: 'Melim', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Meu Amigo Pedro', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Meu Reegae E Roots', band: 'Natiruts', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Rodo Cotidiano', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Morena', band: 'Vitor Kley', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Mumias', band: 'Biquini Cavadao', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Mundo Animal', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Musica Urbana', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Nao Quero Dinheiro', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Nao Sei Viver Sem Ter Voce', band: 'CPM 22', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Natasha', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Natiruts Regge Power', band: 'Natiruts', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Nos Vamos Invadir Sua Praia', band: 'Ultraje A Rigor', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O Calibre', band: 'Paralamas Do Sucesso', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O Girassol', band: 'Ira', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O Mundo', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O Que Sobrou Do Ceu', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O Sol', band: 'Jota Quest', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O sol', band: 'Vitor Kley', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'O Tempo Nao Para', band: 'Cazuza', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Olhar 43', band: 'RPM', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Olhos Certos', band: 'Detonautas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Onde voce Mora', band: 'Cidade Negra', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Ouvi Dizer', band: 'Melim', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Papa E Pop', band: 'Engenheiros', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Papo De Jacare', band: 'P O Box', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pelados Em Santos', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pescador de Ilusoes', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pintura Intima', band: 'Kid Abelha', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pisando Descalco', band: 'Maneva', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Policia', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Por Enquanto', band: 'Cassia Eller', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Por Onde Andei', band: 'Nando Reis', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Por Voce', band: 'Barao Vermelho', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pra Dizer Adeus', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pra Ser Sincero', band: 'Engenheiros', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Presente De Um Beija-Flor', band: 'Natiruts', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Primavera', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Pupila', band: 'Anavitoria', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Puteiro Em Joao Pessoa', band: 'Raimundos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Quando A Chuva Passar', band: 'Ivete Sangalo', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Quando O Sol Bater Na Janela', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Quando O Sol Se For', band: 'Detonautas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Quase Sem Querer', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Quatro Vezes Você', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Que Nem Mare', band: 'Jorge Vercilo', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Que Pais E Este', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Que vez', band: 'Tihuana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Quero Ser Feliz Também', band: 'Natiruts', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Radio Bla', band: 'Lobao', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Radio pirata', band: 'RPM', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Razoes e Emoçoes', band: 'NX Zero', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Reggae Do Manero', band: 'Raimundos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Resposta', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Robocopy Gay', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Rock Das Aranhas', band: 'Raul Seixas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Saideira', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Sao Paulo', band: '365', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Saudades Do Tempo', band: 'Maneva', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Segredos', band: 'Frejat', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Sem Radar', band: 'LS Jack', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Semana Que Vem', band: 'Pitty', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Sera', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Sinceramente', band: 'Cachorro Grande', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'So Hoje', band: 'Jota Quest', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'So os Loucos Sabem', band: 'Charlie Brown Jr', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'So Por Uma Noite', band: 'Charlie Brown Jr', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'So Rezo', band: 'NX Zero', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Sonifera Ilha', band: 'Titas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Sutilmente', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Te devoro ', band: 'Djavan', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Samurai', band: 'Djavan', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Teatro Dos Vampiros', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Telegrama', band: 'Zeca Baleiro', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Toda Forma de Amor', band: 'Lulu Santos', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Todas as noites', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Trem Bala', band: 'Ana Vilela', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Tropa de Elite', band: 'Tijuana', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Tudo que ela gosta de escutar', band: 'Charlie Brown Jr', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Tudo que vai', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Uma Duas Ou Tres ', band: 'Os Ostras', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Uma Noite e Meia', band: 'Marina Lima', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Vamos Fugir', band: 'Skank  Gilberto Gil', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Versos Simples', band: 'Chimarruts', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Vicios e Virtudes', band: 'Charlie Brown Jr', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Vira-Vira', band: 'Mamonas Assassinas', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Vital E Sua Moto', band: 'Paralamas Do Sucesso', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Você ', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Vou Deixar', band: 'Skank', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Whisky A Go Go', band: 'Roupa Nova', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Com Certeza', band: 'Planta e Raíz', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: 'Eu Sei', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Eu Sei ', band: 'Papas da Lingua', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Geracao Coca-Cola', band: 'Legiao Urbana', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'La Bella De Jour', band: 'Alceu Valenaa', tags: 'rock; Nacional', lyrics: '')
# Song.create!( name: ' Rodo Cotidiano', band: 'O Rappa', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'O sol ', band: 'Vitor Kley', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Onde você Mora (amor igual ao teu)', band: 'Cidade Negra', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Palpite ', band: 'Vanessa Rangel', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Quatro Vezes Voce', band: 'Capital Inicial', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Quero Ser Feliz Tambem', band: 'Natiruts', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Razoes e Emocoes', band: 'NX Zero', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Sera', band: 'Legião Urbana', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Te devoro', band: 'Djavan', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'Voce ', band: 'Tim Maia', tags: 'rock; Nacional', lyrics: '')
# # Song.create!( name: 'A Hard Days Night', band: 'Beatles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'A Little Respet', band: 'Erasure', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'About a Girl', band: 'Nirvana', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'All The Smalls Things', band: 'Blink 182', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'American Idiot', band: 'Green Day', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'American Jesus', band: 'Bad Religion', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Anna`s Song ', band: 'Silverchair', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Anthem For The Year 2000', band: 'Silverchair', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Are You Gonna Go My Way', band: 'Lenny Kravitz', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Back To Black', band: 'Amy Winehouse', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Bad Romance', band: 'Lady Gaga', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Beautiful Day', band: 'U2', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Beggin', band: 'Maneskin', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Behind Blue Eyes', band: 'Limp Biskit', tags: 'rock; Internacional', lyrics: '')
# # Song.create!( name: 'Best of You', band: 'Foo Fighters', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Billie Jean', band: 'Michael Jackson', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Bizarre Love Triangule', band: 'New Order', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Black Hole Sun', band: 'Soundgarden', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Black night', band: 'Deep Puple', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Blinding Lights', band: 'The Weekend', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Blue Suede Shoes', band: 'Elvis Presley', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Boy`s dont cry', band: 'The Cure', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Breakin the law', band: 'Judas Priest', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Breaking The Habbit', band: 'Linkin Park', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Bring Me To Life', band: 'Evanescence', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Broken', band: 'Seether', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Bulls On Parede', band: 'Rage Against The Machine', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'By The Way', band: 'Red Hot Chili Peppers', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Can`t By Me Love', band: 'Beatles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Charlie Brown Parents', band: 'Dishwalla', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Chop Suey', band: 'System Of A Down', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Clocks', band: 'Coldplay', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Cocane', band: 'Eric Clapton', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Complecated', band: 'Avril Lavigne', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Crazy', band: 'Seal', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Dancing With Myself', band: 'Billy Idol', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Daugther', band: 'Pearl Jam', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Cry', band: 'Guns `n` Roses', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Go Away', band: 'Oasis', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Let Me Down', band: 'Beatles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Look Back Anger', band: 'Oasis', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Stop Beliving', band: 'Journey', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Stop Dancing', band: 'Creed', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t Stop Me Now ', band: 'Queen', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Don`t You Forget About Me', band: 'Simple Minds', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Drive', band: 'Incubus', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Easy', band: 'Faith No More', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Enjoy the silencie', band: 'Depeche Mode', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Even Flow', band: 'Pearl Jam', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Everlong', band: 'Foo Fighters', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Everybody Wants the Rule The World', band: 'Tears For Fears', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Everybreath You Take', band: 'Police', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Falling to Pieces', band: 'Faith No More', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Fly Away', band: 'Lenny Kravitz', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Freak On a Leash', band: 'Korn', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Friday I`m Love', band: 'The Cure', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'From Whom The Bells', band: 'Metallica', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Fucking Perfetc', band: 'Pink', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Go Let It Out', band: 'Oasis', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Happy', band: 'Pharrel Williams', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Have you ever see the rain', band: 'Creedence', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Heart Shapped Box', band: 'Nirvana', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Help', band: 'Beatles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Here I Go Again', band: 'Whitesnake', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Here With You', band: '3 Doors Down', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Hero', band: 'Chad Kroeger & Josey Scot', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Highway to hell ', band: 'AC/DC', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Hound Dog', band: 'Elvis Presley', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Hunger Strike', band: 'Temple Of The Dog', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Am The Highway', band: 'Audioslave', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Don`t Wanna Miss A Thing', band: 'Aerosmith', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Love Rock n Roll', band: 'Joan Jett', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Put a Speel On You', band: 'Nina Simone', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Wanna Be Desated', band: 'Ramones', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Want It That Way ', band: 'Backstreet Boys', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I Want To Break Free', band: 'Queen', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I`m With You', band: 'Avril Lavigne', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'I`m Yours', band: 'Jason Marz', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Interstate Love Song', band: 'Stone Temple Pilots', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Iris', band: 'Goo Dools', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Ironic', band: 'Alanis Morrissette', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Is This Love ', band: 'Bob Marley', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Its my life', band: 'Bon Jovi', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Knocking On The Heavens Door`s', band: 'Guns `n` Roses', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'La bamba ', band: 'Riche Valen  Beatles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Last Kiss', band: 'Pearl Jam', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Let It be', band: 'Beatles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Lets Twist Again', band: 'Chubby Checker', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Listen To The Music', band: 'Doobie Brothers', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Livin On A Prayer', band: 'Bon Jovi', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Lonely Boy', band: 'Black Keys', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Lonely Day', band: 'System Of A Down', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Love Ain`t No Stranger', band: 'Whitesnake', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Love Me Two Times', band: 'Doors', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Machine Head', band: 'Bush', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Macho Man', band: 'Village People', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Mama I`m Coming Home', band: 'Ozzy Osbourne', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Man I Feel Like A Woman', band: 'Shania Twain', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Miss You Love', band: 'Silverchair', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Monkey Wrench', band: 'Foo Fighters', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Moves Like Jagger', band: 'Marrom 5', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Mr. Brightside', band: 'The Kilers', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Mr. Jones', band: 'Counting Crows', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'My Immortal', band: 'Evanescene', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'No One Knows', band: 'Qeen Of The Stone Age', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Nothing Else Matters', band: 'Metallica', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Numb', band: 'Linkin Park', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'One Last Breath', band: 'Creed', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Only Excepiton, The', band: 'Paramore', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Otherside', band: 'Red Hot Chili Peppers', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Pain lies', band: 'Live', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Paranoid', band: 'Black Sabbath', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Patience', band: 'Guns `n` Roses', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Perfect', band: 'Ed Sheeran', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Perfect Stranger', band: 'Deep Puple', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Pet Cematary', band: 'Ramones', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Photograph ', band: 'Ed Sheeran', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Photograph ', band: 'Nickelback', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Poison heart', band: 'Ramones', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Pretty Woman', band: 'Roy Orbison', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Proud Mary', band: 'Creedence', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Pure Massacre', band: 'Silverchair', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'R. U. Mine', band: 'Artic Monkeys', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Reason, The', band: 'Hoobastank', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Refuse  ', band: 'Sepultura', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Resist', band: 'Sepultura', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Rehab', band: 'Amy Winehouse', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Roadhouse of blues', band: 'Doors', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Rock And Roll', band: 'Led Zeppelin', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Rock N Roll All Night', band: 'Kiss', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Rolling In The Deep', band: 'Adele', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Roster', band: 'Alice In Chains', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Rude', band: 'Magic', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Seven Nation Arms', band: 'White Stripes', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Sex On Fire', band: 'Kings Of Leon', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Shallow', band: 'Lady Gaga', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'She', band: 'Green Day', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Shine', band: 'Collective Soul', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Shout', band: 'Tears For Fears', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Simple Man', band: 'Lynyrd Skynyrd', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Slither', band: 'Velvet Revolver', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Smoke On The Water', band: 'Deep Puple', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Smooth', band: 'Carlos Santana', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Smooth Criminal', band: 'Michael Jackson', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Somebody Told Me', band: 'The Killers', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Somewhere Only We Know', band: 'Keane', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Song 2', band: 'Blur', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Stand By Me', band: 'B.B. King', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Stand By Me ', band: 'Oasis', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Suedhead', band: 'The Smiths  Morrisey', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Supersonic', band: 'Oasis', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Surfin Bird', band: 'Ramones  Trashmen', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Suspicius Mind', band: 'Elvis Presley', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Sweet Child O Mine', band: 'Guns `n` Roses', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Sweet Dreams', band: 'Eurythmics', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Sweet home Alabama', band: 'Lynyrd Skynyrd', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Symphony Of Destruction', band: 'Megadeth', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Tainted Love', band: 'Soft Cell', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Take On Me', band: 'A-ha', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Territory', band: 'Sepultura', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'The Boy With The Thorn In His Side', band: 'The Smiths', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'The Kids Aren`t Alrigh', band: 'Offspring', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'The one I love', band: 'REM', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'The Scientist', band: 'Coldplay', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'The wall', band: 'Pink Floyd', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Them Bones', band: 'Alice In Chains', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Through glass', band: 'Stone Sour', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Time Like These', band: 'Foo Fighters', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Time Of My Life ', band: 'Bill Medley', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Time Of Your Life', band: 'Green Day', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'To Be With You', band: 'Mr. Big', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Tomorrow', band: 'Silverchair', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Torn', band: 'Natalie Imbruglia', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Toxity', band: 'System Of A Down', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Under Preasure', band: 'Queen', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Uptown Funk', band: 'Bruno Marz', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Use somebody', band: 'Kings Of Leon', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Valerie', band: 'Amy Winehouse', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Vertigo', band: 'U2', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Viva La Vida', band: 'Coldplay', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wake Me Up When The Septmber End', band: 'Green Day', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wannabe', band: 'Spice Girls', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wanted Dead Or Alive', band: 'Bon Jovi', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'War Pigs', band: 'Black Sabbath', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wasting Love', band: 'Iron Maiden', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Watermelon Sugar', band: 'Harry Styles', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'We Are The Champions', band: 'Queen', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Welcome To My Life', band: 'Simples Plan', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'What A Wonderful World', band: 'Joe Ramone', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'When I Come Around', band: 'Green Day', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'When I Was Your Man', band: 'Bruno Marz', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wherever you Will Go', band: 'The Calling', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wicked Game', band: 'Chris Isaak', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'With Arms Wide Open', band: 'Creed', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'With or Without You', band: 'U2', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Wonderwall', band: 'Oasis', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Would', band: 'Alice In Chains', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Y.M.C.A', band: 'Village People', tags: 'rock; Internacional', lyrics: '')
# Song.create!( name: 'Yellow', band: 'Coldplay', tags: 'rock; Internacional', lyrics: '')